"""Write the video's title, description, tags and chapters to a text file.

    python services/orchestrator/write_listing.py --out outputs/videos/X/X.txt

The uploader builds this itself when posting through the API. This file exists
for the manual path: uploading by hand means having the title and description
to hand, and hunting through the repo for where they come from is exactly the
sort of friction that ends with a video posted under its filename.

The text is generated by the uploader's own metadata.ts, not reimplemented
here — two implementations of the same description would drift apart, and the
one that drifted would be this one, because it is the one nobody checks.
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "outputs"
UPLOADER = ROOT / "apps" / "uploader"

# A tiny driver handed to tsx, so the listing comes from the same code the
# uploader posts with.
DRIVER = """
import fs from 'node:fs';
import { generateMetadata } from './metadata';
import { generateChaptersText } from './chapters';
const script = JSON.parse(fs.readFileSync(process.argv[2], 'utf-8'));
const m = generateMetadata(script, []);
let chapters = '';
try { chapters = generateChaptersText(script); } catch { /* optional */ }
const out = [
  'TITLE', '', m.title, '',
  '', 'DESCRIPTION', '', m.description, '',
  '', 'TAGS', '', m.tags.join(', '), '',
].join('\\n') + (chapters ? '\\n\\nCHAPTERS\\n\\n' + chapters + '\\n' : '');
fs.writeFileSync(process.argv[3], out, 'utf-8');
"""


def main() -> int:
    ap = argparse.ArgumentParser(description="Write the listing text beside a video")
    ap.add_argument("--script", default=str(OUT / "script.json"))
    ap.add_argument("--out", default=str(OUT / "listing.txt"))
    args = ap.parse_args()

    script_path = Path(args.script)
    if not script_path.exists():
        print(f"[listing] no script at {script_path}")
        return 2
    if not (UPLOADER / "node_modules").exists():
        print("[listing] uploader dependencies not installed; skipping")
        return 0

    npx = shutil.which("npx") or shutil.which("npx.cmd")
    if not npx:
        print("[listing] npx not found; skipping")
        return 0

    # The driver runs with the uploader as its cwd, so both paths must be
    # absolute or node resolves them against apps/uploader.
    script_abs = script_path.resolve()
    out_abs = Path(args.out).resolve()
    out_abs.parent.mkdir(parents=True, exist_ok=True)

    driver = UPLOADER / "_write_listing.ts"
    driver.write_text(DRIVER, encoding="utf-8")
    try:
        subprocess.check_call(
            [npx, "tsx", driver.name, str(script_abs), str(out_abs)],
            cwd=str(UPLOADER),
        )
    except subprocess.CalledProcessError as exc:
        print(f"[listing] generation failed ({exc.returncode})")
        return 1
    finally:
        driver.unlink(missing_ok=True)

    dest = out_abs
    rel = dest.relative_to(ROOT) if dest.is_relative_to(ROOT) else dest
    print(f"[listing] title + description -> {rel}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
