"""ECO code to opening name, for the codes that actually turn up.

The move-matching book in ``facts.py`` reads ``data/eco.tsv``, which has never
existed — so opening names came back None on every game and the description
printed a bare "Opening: D41", which tells a viewer nothing.

This is the cheap half of the fix: a hand-written map from ECO code to the
name that code denotes. It is deliberately partial. A code with no entry
yields no name, and the description omits the line rather than guessing —
naming an opening wrongly is the same class of error as misattributing a
quote, and just as visible to this audience.

Codes here are the ones a classics pool keeps producing. Add more as they
appear; the test asserts shape, not coverage.
"""

from __future__ import annotations

from typing import Dict, Optional

ECO_NAMES: Dict[str, str] = {
    # A — flank and English
    "A00": "Irregular Opening",
    "A04": "Réti Opening",
    "A05": "Réti Opening",
    "A07": "King's Indian Attack",
    "A10": "English Opening",
    "A13": "English Opening",
    "A15": "English Opening",
    "A16": "English Opening",
    "A20": "English Opening",
    "A25": "English Opening, Sicilian Reversed",
    "A28": "English Opening, Four Knights",
    "A30": "English Opening, Symmetrical",
    "A33": "English Opening, Symmetrical",
    "A34": "English Opening, Symmetrical",
    "A40": "Queen's Pawn Opening",
    "A45": "Queen's Pawn Game",
    "A46": "Queen's Pawn Game",
    "A47": "Queen's Indian Defence",
    "A48": "King's Indian, London System",
    "A50": "Queen's Pawn Game",
    "A53": "Old Indian Defence",
    "A56": "Benoni Defence",
    "A57": "Benko Gambit",
    "A58": "Benko Gambit",
    "A59": "Benko Gambit",
    "A60": "Benoni Defence",
    "A61": "Benoni Defence",
    "A65": "Benoni Defence",
    "A70": "Benoni Defence, Classical",
    "A80": "Dutch Defence",
    "A84": "Dutch Defence",
    "A85": "Dutch Defence",
    "A87": "Dutch Defence, Leningrad",
    "A90": "Dutch Defence",
    # B — semi-open, Caro-Kann and Sicilian
    "B00": "Uncommon King's Pawn Opening",
    "B01": "Scandinavian Defence",
    "B02": "Alekhine's Defence",
    "B03": "Alekhine's Defence",
    "B04": "Alekhine's Defence, Modern",
    "B06": "Modern Defence",
    "B07": "Pirc Defence",
    "B08": "Pirc Defence, Classical",
    "B09": "Pirc Defence, Austrian Attack",
    "B10": "Caro-Kann Defence",
    "B12": "Caro-Kann Defence, Advance",
    "B13": "Caro-Kann Defence, Exchange",
    "B15": "Caro-Kann Defence",
    "B17": "Caro-Kann Defence, Steinitz",
    "B18": "Caro-Kann Defence, Classical",
    "B19": "Caro-Kann Defence, Classical",
    "B20": "Sicilian Defence",
    "B21": "Sicilian Defence, Smith-Morra Gambit",
    "B22": "Sicilian Defence, Alapin",
    "B23": "Sicilian Defence, Closed",
    "B27": "Sicilian Defence",
    "B29": "Sicilian Defence, Nimzowitsch",
    "B30": "Sicilian Defence",
    "B31": "Sicilian Defence, Rossolimo",
    "B32": "Sicilian Defence",
    "B33": "Sicilian Defence, Sveshnikov",
    "B40": "Sicilian Defence",
    "B42": "Sicilian Defence, Kan",
    "B43": "Sicilian Defence, Kan",
    "B44": "Sicilian Defence, Taimanov",
    "B45": "Sicilian Defence, Taimanov",
    "B47": "Sicilian Defence, Taimanov",
    "B48": "Sicilian Defence, Taimanov",
    "B50": "Sicilian Defence",
    "B51": "Sicilian Defence, Moscow",
    "B52": "Sicilian Defence, Moscow",
    "B54": "Sicilian Defence",
    "B56": "Sicilian Defence",
    "B57": "Sicilian Defence, Sozin",
    "B58": "Sicilian Defence, Classical",
    "B60": "Sicilian Defence, Richter-Rauzer",
    "B62": "Sicilian Defence, Richter-Rauzer",
    "B63": "Sicilian Defence, Richter-Rauzer",
    "B64": "Sicilian Defence, Richter-Rauzer",
    "B66": "Sicilian Defence, Richter-Rauzer",
    "B70": "Sicilian Defence, Dragon",
    "B72": "Sicilian Defence, Dragon",
    "B76": "Sicilian Defence, Dragon, Yugoslav Attack",
    "B77": "Sicilian Defence, Dragon, Yugoslav Attack",
    "B78": "Sicilian Defence, Dragon, Yugoslav Attack",
    "B80": "Sicilian Defence, Scheveningen",
    "B81": "Sicilian Defence, Scheveningen, Keres Attack",
    "B82": "Sicilian Defence, Scheveningen",
    "B83": "Sicilian Defence, Scheveningen",
    "B84": "Sicilian Defence, Scheveningen",
    "B85": "Sicilian Defence, Scheveningen",
    "B86": "Sicilian Defence, Sozin",
    "B87": "Sicilian Defence, Sozin",
    "B88": "Sicilian Defence, Sozin",
    "B90": "Sicilian Defence, Najdorf",
    "B92": "Sicilian Defence, Najdorf",
    "B93": "Sicilian Defence, Najdorf",
    "B94": "Sicilian Defence, Najdorf",
    "B96": "Sicilian Defence, Najdorf",
    "B97": "Sicilian Defence, Najdorf, Poisoned Pawn",
    "B98": "Sicilian Defence, Najdorf",
    "B99": "Sicilian Defence, Najdorf",
    # C — open games, French
    "C00": "French Defence",
    "C01": "French Defence, Exchange",
    "C02": "French Defence, Advance",
    "C03": "French Defence, Tarrasch",
    "C05": "French Defence, Tarrasch",
    "C07": "French Defence, Tarrasch",
    "C10": "French Defence",
    "C11": "French Defence, Classical",
    "C15": "French Defence, Winawer",
    "C16": "French Defence, Winawer",
    "C17": "French Defence, Winawer",
    "C18": "French Defence, Winawer",
    "C19": "French Defence, Winawer",
    "C20": "King's Pawn Game",
    "C21": "Danish Gambit",
    "C23": "Bishop's Opening",
    "C25": "Vienna Game",
    "C26": "Vienna Game",
    "C29": "Vienna Gambit",
    "C30": "King's Gambit Declined",
    "C33": "King's Gambit Accepted",
    "C36": "King's Gambit Accepted",
    "C37": "King's Gambit Accepted",
    "C39": "King's Gambit Accepted",
    "C41": "Philidor Defence",
    "C42": "Petrov's Defence",
    "C43": "Petrov's Defence",
    "C44": "King's Pawn Game",
    "C45": "Scotch Game",
    "C46": "Three Knights Opening",
    "C47": "Four Knights Game",
    "C48": "Four Knights Game",
    "C49": "Four Knights Game",
    "C50": "Italian Game",
    "C51": "Evans Gambit",
    "C52": "Evans Gambit",
    "C53": "Italian Game, Giuoco Piano",
    "C54": "Italian Game, Giuoco Piano",
    "C55": "Italian Game, Two Knights Defence",
    "C57": "Italian Game, Two Knights Defence",
    "C60": "Ruy Lopez",
    "C62": "Ruy Lopez, Steinitz",
    "C63": "Ruy Lopez, Schliemann",
    "C65": "Ruy Lopez, Berlin Defence",
    "C66": "Ruy Lopez, Berlin Defence",
    "C67": "Ruy Lopez, Berlin Defence",
    "C68": "Ruy Lopez, Exchange",
    "C69": "Ruy Lopez, Exchange",
    "C70": "Ruy Lopez",
    "C71": "Ruy Lopez",
    "C77": "Ruy Lopez",
    "C78": "Ruy Lopez",
    "C80": "Ruy Lopez, Open",
    "C83": "Ruy Lopez, Open",
    "C84": "Ruy Lopez, Closed",
    "C86": "Ruy Lopez, Worrall Attack",
    "C87": "Ruy Lopez, Closed",
    "C88": "Ruy Lopez, Closed",
    "C89": "Ruy Lopez, Marshall Attack",
    "C90": "Ruy Lopez, Closed",
    "C92": "Ruy Lopez, Closed",
    "C93": "Ruy Lopez, Closed",
    "C95": "Ruy Lopez, Breyer",
    "C96": "Ruy Lopez, Closed",
    "C97": "Ruy Lopez, Chigorin",
    "C98": "Ruy Lopez, Chigorin",
    "C99": "Ruy Lopez, Chigorin",
    # D — closed games and Slav/Grünfeld
    "D00": "Queen's Pawn Game",
    "D02": "Queen's Pawn Game",
    "D04": "Queen's Pawn Game",
    "D06": "Queen's Gambit",
    "D07": "Queen's Gambit Declined, Chigorin",
    "D10": "Slav Defence",
    "D11": "Slav Defence",
    "D12": "Slav Defence",
    "D15": "Slav Defence",
    "D16": "Slav Defence",
    "D17": "Slav Defence",
    "D18": "Slav Defence, Dutch",
    "D19": "Slav Defence, Dutch",
    "D20": "Queen's Gambit Accepted",
    "D23": "Queen's Gambit Accepted",
    "D24": "Queen's Gambit Accepted",
    "D26": "Queen's Gambit Accepted",
    "D27": "Queen's Gambit Accepted",
    "D30": "Queen's Gambit Declined",
    "D31": "Queen's Gambit Declined",
    "D32": "Queen's Gambit Declined, Tarrasch",
    "D33": "Queen's Gambit Declined, Tarrasch",
    "D34": "Queen's Gambit Declined, Tarrasch",
    "D35": "Queen's Gambit Declined, Exchange",
    "D36": "Queen's Gambit Declined, Exchange",
    "D37": "Queen's Gambit Declined",
    "D38": "Queen's Gambit Declined, Ragozin",
    "D39": "Queen's Gambit Declined, Vienna",
    "D40": "Queen's Gambit Declined, Semi-Tarrasch",
    "D41": "Queen's Gambit Declined, Semi-Tarrasch",
    "D42": "Queen's Gambit Declined, Semi-Tarrasch",
    "D43": "Semi-Slav Defence",
    "D44": "Semi-Slav Defence, Botvinnik",
    "D45": "Semi-Slav Defence",
    "D46": "Semi-Slav Defence",
    "D47": "Semi-Slav Defence, Meran",
    "D48": "Semi-Slav Defence, Meran",
    "D49": "Semi-Slav Defence, Meran",
    "D50": "Queen's Gambit Declined",
    "D52": "Queen's Gambit Declined, Cambridge Springs",
    "D53": "Queen's Gambit Declined",
    "D55": "Queen's Gambit Declined",
    "D58": "Queen's Gambit Declined, Tartakower",
    "D59": "Queen's Gambit Declined, Tartakower",
    "D60": "Queen's Gambit Declined, Orthodox",
    "D63": "Queen's Gambit Declined, Orthodox",
    "D64": "Queen's Gambit Declined, Orthodox",
    "D66": "Queen's Gambit Declined, Orthodox",
    "D67": "Queen's Gambit Declined, Orthodox",
    "D70": "Grünfeld Defence",
    "D71": "Grünfeld Defence",
    "D76": "Grünfeld Defence",
    "D78": "Grünfeld Defence",
    "D80": "Grünfeld Defence",
    "D82": "Grünfeld Defence",
    "D85": "Grünfeld Defence, Exchange",
    "D86": "Grünfeld Defence, Exchange",
    "D87": "Grünfeld Defence, Exchange",
    "D90": "Grünfeld Defence",
    "D94": "Grünfeld Defence",
    "D97": "Grünfeld Defence, Russian",
    # E — Indian defences
    "E00": "Catalan Opening",
    "E01": "Catalan Opening",
    "E04": "Catalan Opening, Open",
    "E05": "Catalan Opening, Open",
    "E06": "Catalan Opening, Closed",
    "E08": "Catalan Opening, Closed",
    "E11": "Bogo-Indian Defence",
    "E12": "Queen's Indian Defence",
    "E14": "Queen's Indian Defence",
    "E15": "Queen's Indian Defence",
    "E17": "Queen's Indian Defence",
    "E18": "Queen's Indian Defence",
    "E20": "Nimzo-Indian Defence",
    "E21": "Nimzo-Indian Defence, Three Knights",
    "E24": "Nimzo-Indian Defence, Sämisch",
    "E26": "Nimzo-Indian Defence, Sämisch",
    "E32": "Nimzo-Indian Defence, Classical",
    "E33": "Nimzo-Indian Defence, Classical",
    "E34": "Nimzo-Indian Defence, Classical",
    "E38": "Nimzo-Indian Defence, Classical",
    "E40": "Nimzo-Indian Defence, Rubinstein",
    "E41": "Nimzo-Indian Defence, Rubinstein",
    "E42": "Nimzo-Indian Defence, Rubinstein",
    "E43": "Nimzo-Indian Defence, Rubinstein",
    "E45": "Nimzo-Indian Defence, Rubinstein",
    "E46": "Nimzo-Indian Defence, Rubinstein",
    "E48": "Nimzo-Indian Defence, Rubinstein",
    "E49": "Nimzo-Indian Defence, Rubinstein",
    "E51": "Nimzo-Indian Defence, Rubinstein",
    "E53": "Nimzo-Indian Defence, Rubinstein",
    "E54": "Nimzo-Indian Defence, Rubinstein",
    "E55": "Nimzo-Indian Defence, Rubinstein",
    "E56": "Nimzo-Indian Defence, Rubinstein",
    "E58": "Nimzo-Indian Defence, Rubinstein",
    "E60": "King's Indian Defence",
    "E61": "King's Indian Defence",
    "E62": "King's Indian Defence, Fianchetto",
    "E63": "King's Indian Defence, Fianchetto",
    "E67": "King's Indian Defence, Fianchetto",
    "E68": "King's Indian Defence, Fianchetto",
    "E70": "King's Indian Defence",
    "E71": "King's Indian Defence, Makogonov",
    "E73": "King's Indian Defence, Averbakh",
    "E74": "King's Indian Defence, Averbakh",
    "E75": "King's Indian Defence, Averbakh",
    "E76": "King's Indian Defence, Four Pawns Attack",
    "E80": "King's Indian Defence, Sämisch",
    "E81": "King's Indian Defence, Sämisch",
    "E83": "King's Indian Defence, Sämisch",
    "E84": "King's Indian Defence, Sämisch",
    "E86": "King's Indian Defence, Sämisch",
    "E87": "King's Indian Defence, Sämisch",
    "E90": "King's Indian Defence",
    "E91": "King's Indian Defence, Classical",
    "E92": "King's Indian Defence, Classical",
    "E94": "King's Indian Defence, Classical",
    "E95": "King's Indian Defence, Classical",
    "E97": "King's Indian Defence, Mar del Plata",
    "E98": "King's Indian Defence, Mar del Plata",
    "E99": "King's Indian Defence, Mar del Plata",
}


def name_for(eco: Optional[str]) -> Optional[str]:
    """The opening this ECO code denotes, or None when we do not know."""
    code = (eco or "").strip().upper()
    return ECO_NAMES.get(code)
